### ISSUE TITLE
render not working

### ISSUE THREAD

**Issue by jcpny1** [learn-co-curriculum/validations-with-form_tag-rails-lab#7]
As cloned, I couldn't get render to work when using rails server with Internet Explorer. (redirect_to worked ok.) When I 'render :new', I get response GET /authors path not found. When I 'render :edit', I get the show page with the unedited values displayed. The learn tests ran with 0 errors and appear to render properly. This problem applies to the previous less as well (Validations with form_tag).

**Comment by jcpny1** [comment]
this problem applies to the previous less as well. Validations with form_tag.

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, or maybe not fully grasping what is wrong in the curriculum, so I'm going to close it for now. It may have been fixed with upgrades to Rails gems.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
